### ISSUE TITLE
gaia.best 주소 치면 500error 뜨는 오류!!

### ISSUE THREAD

**Issue by KrGil** [ddit301/gaia#228]
http://222.114.124.74/gaia// 뒤에 /가 자꾸 붙어요!! 저번에 수정한 듯 한데 아직 적용이 안된 것일까요?!

**Comment by ShanePark** [comment]
www.gaia.best 는 괜찮던데 best.gaia 가 그렇더라고요. 뭐가 문젠지 체크해볼게요

**Comment by KrGil** [comment]
넵!

**Comment by ShanePark** [comment]
해결완료
