### ISSUE TITLE
overview 페이지의 동기처리 비동기화

### ISSUE THREAD

**Issue by ShanePark** [ddit301/gaia#241]
임시로 페이지 돌리며 페이지가 리프레시되는 버튼 2개가 발생됨.
두개 버튼 모두 비동기 처리.
member.MEM_ID 를 활용 하면 간단히 될듯.

소요 예상시간: 5 분 이하

**Comment by KrGil** [comment]
무슨말이에요?! 주말에 대전 한번 갈까요?!

**Comment by ShanePark** [comment]
아아 지금 overview 페이지를 프로젝트 목록 나오는 페이지로 돌려둔게 버튼 눌렀을 때 화면 리프레쉬 되어서 그거 없애려고요 ㅋㅋ. 제가 오늘 퇴근하면 고쳐둘게요
주말에 한번 놀러와서 우분투 깔아가세요 ~

**Comment by ShanePark** [comment]
issac 이랑 같이 엘지 컴터 나란히 세워놓고 누구꺼에 더 먼저 우분투 올라가나 보면 되겠다. 하면서 중국집 배달시켜서 후루룩~
